Game.create!(title: "Apex Legends", description: "")
Game.create!(title: "VALORANT", description: "")
Game.create!(title: "Counter-Strike 2", description: "")
Game.create!(title: "OverWatch2", description: "")
Game.create!(title: "Fortnite", description: "")
Game.create!(title: "Tom Clancy’s Rainbow Six Siege", description: "")
Game.create!(title: "Escape from Tarkov", description: "")
Game.create!(title: "PUBG: BATTLEGROUNDS", description: "")
Game.create!(title: "Call of Duty: Modern Warfare III", description: "")
Game.create!(title: "Splatoon 3", description: "")
